#!/bin/bash

# input is a git branch name
# output is a commit message
exec sed \
    -e 's?^[a-z]*/\(feature\|bugfix\)/??g' \
    -e "s|}sD>|/|g" \
    -e "s/}dD>/./g" \
    -e "s/_''_/"'"'"/g" \
    -e 's/_/ /g' \
    -e 's/}BSBS>/\\/g' \
    -e 's/}DD>/../g' \
    -e 's/----/:/g' \
    -e 's/((((/\[/g' \
    -e 's/))))/\]/g' \
    -e 's/}t>/~/g' \
    -e 's/}\.>/?/g' \
    -e 's/=#=/\^/g' \
    -e 's?}SS>?*?g' \
    -e 's?}SD>?/.?g' \
    -e 's?}S>?//?g' \
    -e 's/^}0D>/\./g' \
    -e 's/}C>/@{/g' \
    -e 's|}L>|.lock|g'
