#!/bin/bash
HERE=$(dirname ${BASH_SOURCE[0]})
. ${HERE}/fixpath

mkdir -p ${HERE}/etc
if [ ! -f "${HERE}/etc/difffileviewer" ] ; then
    echo cat
    exit 0
fi
cat ${HERE}/etc/difffileviewer | head -1
