#!/bin/bash
HERE=$(dirname ${BASH_SOURCE[0]})
. ${HERE}/fixpath

if ! checkDANKEY ; then
    exit 1
fi

if ! allcommitted ; then
    >&2 echo "Local status is not safe enough to run this command."
    exit 1
fi

aborted=notaborted

career=nocareer
if [ $aborted != aborted ] ; then
    echo Testing the pull request will not be blocked by conflicts ...
    # Generate a safe branch off the target and merge into it
    preparebranchforpullrequest.sh $@ | tee /tmp/preparebranchforpullrequest$$
    if [ "${PIPESTATUS[0]}" = "1" ] ; then
        aborted=aborted
    else
        if grep '^USER REQUESTED CAREER TO END' /tmp/preparebranchforpullrequest$$ > /dev/null 2>&1 ; then
            career=career
        fi
    fi
fi
\rm /tmp/preparebranchforpullrequest$$

if [ $aborted != aborted ] ; then
    # create a pull request on bitbucket from that safe branch to the target
    if [ $career = career ] ; then
        if ! ( yes | createpullrequest $@ ) ; then
            aborted=aborted
        fi
    elif ! createpullrequest $@ ; then
        aborted=aborted
    fi
fi

if [ $aborted != aborted ] ; then
    # merge that pull request no-ff
    if [ $career = career ] ; then
        if ! ( yes | mergepullrequest $@ --strategyId=no-ff ) ; then
            aborted=aborted
        fi
    elif ! mergepullrequest $@ --strategyId=no-ff ; then
        aborted=aborted
    fi
fi

# delete staging branches
runCleanup.sh
