#!/bin/bash
HERE=$(dirname ${BASH_SOURCE[0]})
. ${HERE}/fixpath

if ! checkDANKEY ; then
    exit 1
fi

echo Please enter the email address you use for bitbucket login.
echo -n 'Email: '
read emailaddress

if [ -z "$emailaddress" ] ; then
    >&2 echo No email adress entered.  Aborting.
    exit 1
fi

echo Please enter the password you use for bitbucket login.
echo -n 'Password: '
read -s password

if [ -z "$password" ] ; then
    >&2 echo No email password entered.  Aborting.
    exit 1
fi

mkdir -p ${HERE}/etc
echo ${emailaddress}:${password} | enc > ${HERE}/etc/jiracredentials
echo Your jira credentials have been encrypted into ${HERE}/etc/jiracredentials using your DANKEY
